# Generated by Django 6.0.1 on 2026-01-18 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_users', '0003_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
