# Generated by Django 6.0.1 on 2026-01-16 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('a_brinquedos', '0002_alter_brinquedo_tipo'),
        ('a_clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemLocacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brinquedo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_brinquedos.brinquedo')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_locacao', models.DateField(auto_now_add=True)),
                ('data_montagem', models.DateTimeField()),
                ('data_devolucao', models.DateTimeField()),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('brinquedo', models.ManyToManyField(through='a_locacoes.ItemLocacao', to='a_brinquedos.brinquedo')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locacoes', to='a_clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='itemlocacao',
            name='locacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a_locacoes.locacao'),
        ),
        migrations.AlterUniqueTogether(
            name='itemlocacao',
            unique_together={('locacao', 'brinquedo')},
        ),
    ]
