# Generated by Django 6.0.1 on 2026-01-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='data_locacao',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
