# Generated by Django 6.0.1 on 2026-01-20 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0004_locacao_criado_por_alter_locacao_cliente'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='criado_por',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='locacoes_criadas', to=settings.AUTH_USER_MODEL),
        ),
    ]
