# Generated by Django 6.0.1 on 2026-01-21 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0006_alter_locacao_criado_por'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endereco',
            name='bairro',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='cep',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='complemento',
        ),
        migrations.RemoveField(
            model_name='endereco',
            name='estado',
        ),
    ]
