# Generated by Django 6.0.1 on 2026-03-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0007_remove_endereco_bairro_remove_endereco_cep_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
