# Generated by Django 6.0.1 on 2026-04-24 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0008_locacao_cancelada'),
    ]

    operations = [
        migrations.AddField(
            model_name='locacao',
            name='uuid_publico',
            field=models.UUIDField(editable=False, null=True),
        ),
    ]
