# Generated by Django 6.0.1 on 2026-04-24 16:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0009_locacao_uuid_publico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locacao',
            name='uuid_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
