# Generated by Django 6.0.1 on 2026-04-24 17:05

import uuid
from django.db import migrations, models

def gen_uuid(apps, schema_editor):
    Locacao = apps.get_model('a_locacoes', 'Locacao')
    for row in Locacao.objects.all():
        row.uuid_publico = uuid.uuid4()
        row.save(update_fields=['uuid_publico'])

class Migration(migrations.Migration):

    dependencies = [
        ('a_locacoes', '0010_alter_locacao_uuid_publico'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name='locacao',
            name='uuid_publico',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
