# Generated by Django 6.0.1 on 2026-01-16 16:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('numero_celular', models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='Use o formato (99) 99999-9999', regex='^\\(\\d{2}\\) \\d{5}-\\d{4}$')])),
            ],
        ),
    ]
