# Generated by Django 6.0.1 on 2026-01-10 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brinquedo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('pula-pula', 'Pula-Pula'), ('cama-elastica', 'Cama Elástica')], max_length=50)),
                ('disponivel', models.BooleanField(default=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
    ]
