# Generated by Django 6.0.1 on 2026-01-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_brinquedos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='tipo',
            field=models.CharField(choices=[('cama-elastica', 'Cama Elástica'), ('piscina-de-bolinhas', 'Piscina de Bolinhas')], max_length=50),
        ),
    ]
