# Generated by Django 6.0.1 on 2026-01-16 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('a_brinquedos', '0002_alter_brinquedo_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brinquedo',
            name='disponivel',
        ),
    ]
