# Generated by Django 6.0.1 on 2026-01-19 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_brinquedos', '0003_remove_brinquedo_disponivel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='tipo',
            field=models.CharField(choices=[('cama-elastica 3m', 'Cama Elástica - 3 metros'), ('cama-elastica 5m', 'Cama Elástica - 5 metros'), ('piscina-de-bolinhas', 'Piscina de Bolinhas')], max_length=50),
        ),
    ]
