# Generated by Django 6.0.1 on 2026-01-19 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('a_brinquedos', '0004_alter_brinquedo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brinquedo',
            name='tipo',
            field=models.CharField(choices=[('cama-elastica-2,49-metros', 'Cama Elástica - 2,49 metros'), ('cama-elastica-3-metros', 'Cama Elástica - 3 metros'), ('cama-elastica-5-metros', 'Cama Elástica - 5 metros'), ('piscina-de-bolinhas', 'Piscina de Bolinhas')], max_length=50),
        ),
    ]
